"""add imgurl

Revision ID: 400febf16e5e
Revises: 
Create Date: 2023-05-14 07:26:08.355029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '400febf16e5e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_url', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('img_url')

    # ### end Alembic commands ###
